name: appmorritos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.0
  lottie: ^2.7.0
  shared_preferences: ^2.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/Logo.png


flutter:
  uses-material-design: true
  assets:
    - assets/fonts/ComicNeue/
    - assets/images/
    - assets/icons/Logo.png
    - assets/sonidos/puzzlegame.mp3
    - assets/sonidos/Contar.mp3
    - assets/sonidos/uno.mp3
    - assets/sonidos/Dos.mp3
    - assets/sonidos/Tres.mp3
    - assets/sonidos/Cuatro.mp3
    - assets/sonidos/Cinco.mp3
    - assets/sonidos/Seis.mp3
    - assets/sonidos/Siete.mp3
    - assets/sonidos/Ocho.mp3
    - assets/sonidos/Nueve.mp3
    - assets/sonidos/Diez.mp3
    - assets/sonidos/correcto.mp3
    - assets/sonidos/incorrecto.mp3
    - assets/sonidos/Sumas.mp3
    - assets/sonidos/Restas.mp3
  fonts:
    - family: ComicNeue
      fonts:
        - asset: assets/fonts/ComicNeue/ComicNeue-Regular.ttf
        - asset: assets/fonts/ComicNeue/ComicNeue-Bold.ttf
        - asset: assets/fonts/ComicNeue/ComicNeue-BoldItalic.ttf
        - asset: assets/fonts/ComicNeue/ComicNeue-Italic.ttf
        - asset: assets/fonts/ComicNeue/ComicNeue-Light.ttf
        - asset: assets/fonts/ComicNeue/ComicNeue-LightItalic.ttf