name: appmorritos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^4.1.0
  lottie: ^2.7.0
  shared_preferences: ^2.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/Logo.png


flutter:
  uses-material-design: true
  assets:
    - assets/fonts/ComicNeue/
    - assets/images/
    - assets/icons/Logo.png
  fonts:
    - family: ComicNeue
      fonts:
        - asset: assets/fonts/ComicNeue/ComicNeue-Regular.ttf
        - asset: assets/fonts/ComicNeue/ComicNeue-Bold.ttf
        - asset: assets/fonts/ComicNeue/ComicNeue-BoldItalic.ttf
        - asset: assets/fonts/ComicNeue/ComicNeue-Italic.ttf
        - asset: assets/fonts/ComicNeue/ComicNeue-Light.ttf
        - asset: assets/fonts/ComicNeue/ComicNeue-LightItalic.ttf